a = int(input())
print('{:b}'.format(a))
x = float(input('x:'))
y = float(input('y:'))
z = float(input('z:'))

print('abs(x)', abs(x))
print('bool(x)', bool(x))
print('divmod(x, y)', divmod(x, y))
print('min', min(x, y))
print('max', max(x, y))
print('pow', pow(x, y))
print('round 2', round(x, 2))
print('round 3', round(x, 3))
print('sum', sum(x, y, z))
